force-app/main/default/objects/Product2/fields/Calendar_Month_Cost__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Month_Cost__c</fullName>
    <description>Cost per Calendar Month</description>
    <inlineHelpText>Cost per Calendar Month</inlineHelpText>
    <label>Calendar Month Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost</description>
    <inlineHelpText>Card Replacement Cost</inlineHelpText>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Other_Currency_ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>Other_Currency_ATM_Fee__c</fullName>
    <description>ATM Fee in other currencies</description>
    <inlineHelpText>ATM Fee in other currencies</inlineHelpText>
    <label>Other Currency ATM Fee</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ContactProductInfoTest.cls
/**
 * @description       : Apex Test class for ContactProductInfo
 * @last modified on  : 01-10-2023
**/
@IsTest
private with sharing class ContactProductInfoTest {

    @TestSetup
    static void makeData() {
        TestDataFactory.generateContactProductInfoDataSet('external-id');
    }
    
    @IsTest
    private static void testContactProductInfoIsRetrievedWhenProductTypeAndCountryIsFullfilledOnContact() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
        Product2 selectedProduct = ContactProductInfo.getSelectedProduct(testCase.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, selectedProduct, 'selected product shoudlnt be null');
        System.assertEquals(selectedProduct.Calendar_Month_Cost__c, 0, 'retrieved selected product info is wrong');
        System.assertEquals(selectedProduct.Other_Currency_ATM_Fee__c, 1.70, 'retrieved selected product info is wrong');
        System.assertEquals(selectedProduct.Card_Replacement_Cost__c, 6, 'retrieved selected product info is wrong');
    }

    @IsTest
    private static void testContactProductInfoIsNotRetrievedWhenProductTypeOrCountryIsNotFullfilledOnContact() {
        Case testCase = [SELECT Id, ContactId FROM Case LIMIT 1];

        Contact testContact = new Contact(
            Id = testCase.ContactId,
            Home_Country__c = null
        );
        update testContact;

        Test.startTest();
        Product2 selectedProduct = ContactProductInfo.getSelectedProduct(testCase.Id);
        Test.stopTest();

        System.assertEquals(null, selectedProduct, 'selected product was found when shouldnt');
    }

    @IsTest
    private static void testContactProductInfoIsNotRetrievedWhenProductTypeAndCountryDoesntMatchAnExistentActiveProduct() {
        Case testCase = [SELECT Id, ContactId FROM Case LIMIT 1];

        Contact testContact = new Contact(
            Id = testCase.ContactId,
            Home_Country__c = 'FR'
        );
        update testContact;

        Test.startTest();
        Product2 selectedProduct = ContactProductInfo.getSelectedProduct(testContact.Id);
        Test.stopTest();

        System.assertEquals(null, selectedProduct, 'selected product was found when shouldnt');
    }

    @IsTest
    private static void testContactProductInfoThrowExceptionWhenInvalidContactIdIsPassed() {
        Test.startTest();
        try {
            ContactProductInfo.getSelectedProduct('INVALID');
        } catch (Exception e) {
            System.assertEquals('System.StringException', e.getTypeName(), 'An string exception should be thrown: ' + e.getMessage());
            return;
        }
        System.assert(false, 'first exception should be thrown so this assert shouldnt be fired');
        Test.stopTest();
    }
}