force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External UUID of the Contact</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer&apos;s chosen product</description>
    <inlineHelpText>Customer&apos;s chosen product</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_Country__c.field-meta.xml
<CustomField>
    <fullName>Available_Country__c</fullName>
    <label>Available Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Calendar_Month_Cost__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Month_Cost__c</fullName>
    <description>Cost per Calendar Month</description>
    <inlineHelpText>Cost per Calendar Month</inlineHelpText>
    <label>Calendar Month Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost</description>
    <inlineHelpText>Card Replacement Cost</inlineHelpText>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Other_Currency_ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>Other_Currency_ATM_Fee__c</fullName>
    <description>ATM Fee in other currencies</description>
    <inlineHelpText>ATM Fee in other currencies</inlineHelpText>
    <label>Other Currency ATM Fee</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>Countries where N26 products are available</description>
    <masterLabel>Home Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @description       : Data Factory class helper for Test classes
 * @last modified on  : 01-12-2023
**/
@IsTest
public with sharing class TestDataFactory {

    /**
    * @description Dataset generator for Contact Product Info module Test classes: ContactProductInfoTest, WSContacts_v1Test
    * @param contactExternalId -> The contact external Id (required for Contacts)
    **/
    public static void generateContactProductInfoDataSet(String contactExternalId) {
        Account testAccount = new Account(
            Name = 'N26 Test Customer'
        );
        insert testAccount;

        Contact testContact = new Contact(
            LastName = 'Test Contact',
            AccountId = testAccount.Id,
            Home_Country__c = 'ES',
            Product__c = 'Standard',
            External_Id__c = contactExternalId
        );
        insert testContact;

        Case caseContact = new Case(
            ContactId = testContact.Id
        );
        insert caseContact;

        Product2 standardESProd = new Product2(
            Name = 'Standard',
            ProductCode = 'STD-ES',
            Available_Country__c = 'ES',
            Calendar_Month_Cost__c = 0,
            Other_Currency_ATM_Fee__c = 1.70,
            Card_Replacement_Cost__c = 6,
            CurrencyIsoCode = 'EUR',
            IsActive = true
        );

        Product2 blackESProd = new Product2(
            Name = 'Black',
            ProductCode = 'BLK-ES',
            Available_Country__c = 'ES',
            Calendar_Month_Cost__c = 9.90,
            Other_Currency_ATM_Fee__c = 0,
            Card_Replacement_Cost__c = 6,
            CurrencyIsoCode = 'EUR',
            IsActive = true
        );

        Product2 metalESProd = new Product2(
            Name = 'Metal',
            ProductCode = 'MTL-ES',
            Available_Country__c = 'ES',
            Calendar_Month_Cost__c = 16.9,
            Other_Currency_ATM_Fee__c = 0,
            Card_Replacement_Cost__c = 45,
            CurrencyIsoCode = 'EUR',
            IsActive = true
        );
        insert new List<Product2>{standardESProd, blackESProd, metalESProd};
    }
}