force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer&apos;s chosen product</description>
    <inlineHelpText>Customer&apos;s chosen product</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_Country__c.field-meta.xml
<CustomField>
    <fullName>Available_Country__c</fullName>
    <label>Available Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Calendar_Month_Cost__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Month_Cost__c</fullName>
    <description>Cost per Calendar Month</description>
    <inlineHelpText>Cost per Calendar Month</inlineHelpText>
    <label>Calendar Month Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost</description>
    <inlineHelpText>Card Replacement Cost</inlineHelpText>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Other_Currency_ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>Other_Currency_ATM_Fee__c</fullName>
    <description>ATM Fee in other currencies</description>
    <inlineHelpText>ATM Fee in other currencies</inlineHelpText>
    <label>Other Currency ATM Fee</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>Countries where N26 products are available</description>
    <masterLabel>Home Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactProductInfo.cls
/**
 * @description       : Apex Controller for ContactProductInfo LWC. Retrieves the selected Product information from the Contact info in a Case
 * @last modified on  : 01-10-2023
**/
public with sharing class ContactProductInfo {
    
    /**
    * @description Returns a matching active Product for a Case's contact by a Product type and a Home Country
    * @author AM | 01-10-2023 
    * @param caseId -> The current Case Id related to the Contact
    * @return Product2 -> The matching product for the selected Product type and Home Country on the Case's Contact 
    **/
    @AuraEnabled
    public static Product2 getSelectedProduct(Id caseId) {
        Product2 selectedProduct;
        List<Case> currentCase = [
            SELECT 
                Contact.Home_Country__c,
                Contact.Product__c
            FROM Case
            WHERE Id = :caseId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];

        if(!currentCase.isEmpty()) {
            List<Product2> matchingProduct = [
                SELECT
                    Name,
                    toLabel(Available_Country__c),
                    Calendar_Month_Cost__c,
                    Other_Currency_ATM_Fee__c,
                    Card_Replacement_Cost__c
                FROM Product2
                WHERE IsActive = true
                    AND Name = :currentCase[0].Contact.Product__c
                    AND Available_Country__c = :currentCase[0].Contact.Home_Country__c
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            selectedProduct = !matchingProduct.isEmpty() ? matchingProduct[0] : null;
        }
        return selectedProduct;
    }
}